# Site settings
title: Topología
email: 
description: > # this means to ignore newlines until "baseurl:"
  Curso de Topología en la licenciatura de matemáticas aplicadas,
  UAEH, enero-junio 2016.
baseurl: "/topologia" # the subpath of your site, e.g. /blog/
url: "http://rvf0068.github.io/topologia" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: mateclases
disqus_show_comment_count: false
